// Modelo lógico do Sumário de Alta (Portaria SAES/MS nº 701/2022), derivado do
// SA-IG da RNDS (o modelo de informação publicado no SA-IG está vazio) e
// mapeado para o BR-Core e para o SA-IG. Gerado por scripts/gerar_modelo_logico.py.

Logical: SumarioAltaML
Id: sumario-alta-ml
Title: "Modelo lógico do Sumário de Alta"
Description: "Modelo de informação do Sumário de Alta hospitalar, independente de tecnologia, com o mapeamento de cada elemento para o BR-Core (refatoração) e para o SA-IG da RNDS (legado)."
* ^status = #draft
* ^experimental = true
* documento 1..1 BackboneElement "Documento" "Dados do documento Sumário de Alta como um todo."
* documento.identificador 1..1 Identifier "Identificador do documento" "Identificador persistente do documento, igual em todas as transmissões."
* documento.dataHora 1..1 dateTime "Data e hora do documento" "Momento de emissão do documento."
* documento.situacao 1..1 code "Situação do documento" "final, retificado ou anulado."
* documento.tipo 1..1 CodeableConcept "Tipo de documento" "Sumário de Alta."
* documento.autor 1..* Reference(Resource) "Autor" "Profissional responsável pela alta."
* documento.atestador 0..1 Reference(Resource) "Atestador legal" "Quem autentica o documento."
* documento.custodiante 1..1 Reference(Resource) "Estabelecimento custodiante" "Estabelecimento (CNES) responsável pela guarda."
* documento.documentoSubstituido 0..1 Reference(Resource) "Documento substituído" "Documento retificado por este."
* individuo 1..1 Reference(Resource) "Indivíduo" "Paciente do sumário."
* contatoAssistencial 1..1 BackboneElement "Contato assistencial (internação)" "Dados da internação a que o sumário se refere."
* contatoAssistencial.modalidade 1..1 CodeableConcept "Modalidade assistencial" "Modalidade do atendimento."
* contatoAssistencial.modalidadeTelessaude 0..1 CodeableConcept "Modalidade de telessaúde" "Quando o atendimento envolve telessaúde."
* contatoAssistencial.carater 1..1 CodeableConcept "Caráter do atendimento" "Eletivo, urgência etc."
* contatoAssistencial.admissao 1..1 dateTime "Momento da admissão" "Data e hora da admissão."
* contatoAssistencial.alta 1..1 dateTime "Momento da alta" "Data e hora do desfecho."
* contatoAssistencial.procedencia 1..1 CodeableConcept "Procedência" "Origem do paciente."
* contatoAssistencial.motivoDesfecho 1..1 CodeableConcept "Motivo do desfecho" "Alta, óbito, transferência etc."
* contatoAssistencial.motivoAtendimento 0..1 Reference(Resource) "Motivo do atendimento" "Condição que motivou a internação."
* contatoAssistencial.profissional 1..* BackboneElement "Profissional participante" "Profissionais do atendimento e da alta."
* contatoAssistencial.profissional.papel 1..1 CodeableConcept "Tipo de participação" "Admissão, atendimento, alta."
* contatoAssistencial.profissional.individuo 1..1 Reference(Resource) "Profissional" "Profissional participante."
* contatoAssistencial.equipe 0..1 Reference(Resource) "Equipe" "Equipe responsável."
* contatoAssistencial.local 0..1 Reference(Resource) "Local de atendimento" "Unidade ou leito."
* contatoAssistencial.estabelecimento 1..1 Reference(Resource) "Estabelecimento" "Estabelecimento (CNES) do atendimento."
* contatoAssistencial.contatoAnterior 0..1 Reference(Resource) "Contato assistencial anterior" "Atendimento que originou este."
* contatoAssistencial.resumoEvolucao 1..1 string "Resumo da evolução clínica" "Narrativa da evolução durante a internação."
* contatoAssistencial.informacoesAdicionais 0..1 string "Informações adicionais" "Informações complementares."
* diagnosticoAdmissao 0..* BackboneElement "Diagnóstico da admissão" "Diagnósticos ou problemas na admissão."
* diagnosticoAdmissao.codigo 1..1 CodeableConcept "Diagnóstico ou problema" "CID-10."
* diagnosticoAdmissao.situacao 1..1 CodeableConcept "Estado da resolução" "Ativo, resolvido etc."
* diagnosticoAdmissao.nota 0..1 string "Nota" "Observação."
* diagnosticoAvaliado 0..* BackboneElement "Diagnóstico avaliado" "Diagnósticos ou problemas avaliados durante a internação."
* diagnosticoAvaliado.codigo 1..1 CodeableConcept "Diagnóstico ou problema" "CID-10."
* diagnosticoAvaliado.papel 0..1 CodeableConcept "Principal ou secundário" "Papel do diagnóstico na internação."
* diagnosticoAvaliado.situacao 1..1 CodeableConcept "Estado da resolução" "Ativo, resolvido etc."
* alergia 0..* BackboneElement "Alergia ou reação adversa" "Alergias e intolerâncias conhecidas ou ocorridas."
* alergia.agente 1..1 CodeableConcept "Agente ou substância" "Substância (ou o tipo, se a substância não é conhecida)."
* alergia.categoria 1..1 code "Categoria do agente" "Alimento, medicamento, ambiente, biológico."
* alergia.tipo 0..1 code "Tipo de reação" "Alergia ou intolerância."
* alergia.grauCerteza 0..1 CodeableConcept "Grau de certeza" "Confirmada, não confirmada etc."
* alergia.criticidade 0..1 code "Criticidade" "Baixa, alta, não avaliável."
* alergia.instalacao 0..1 dateTime "Data da instalação" "Início da alergia ou reação."
* alergia.manifestacao 0..* CodeableConcept "Manifestação" "Sinais e sintomas."
* alergia.evolucao 0..1 string "Evolução" "Evolução da alergia ou reação."
* procedimento 0..* BackboneElement "Procedimento realizado" "Procedimentos realizados na internação."
* procedimento.codigo 1..1 CodeableConcept "Procedimento" "Tabela SUS ou TUSS 22."
* procedimento.situacao 1..1 code "Estado do procedimento" "Concluído, não realizado etc."
* procedimento.momento 1..1 dateTime "Momento da realização" "Data e hora ou período."
* procedimento.quantidade 0..1 integer "Quantidade" "Quantidade realizada."
* procedimento.executante 1..* Reference(Resource) "Executante" "Profissional executante."
* procedimento.funcao 0..1 CodeableConcept "Função do executante" "Cirurgião, auxiliar, anestesista."
* procedimento.estabelecimentoTerceiro 0..1 Reference(Resource) "Estabelecimento terceiro" "Quando realizado por terceiro."
* procedimento.autorizacao 0..1 Identifier "Número de autorização" "Autorização do procedimento."
* procedimento.resultado 0..1 string "Resultado ou observações" "Resultado do procedimento."
* prescricao 0..* BackboneElement "Prescrição de alta" "Medicamentos prescritos na alta."
* prescricao.medicamento 1..1 Reference(Resource) "Medicamento" "Medicamento prescrito."
* prescricao.dataPrescricao 1..1 dateTime "Data e hora da prescrição" "Data e hora da prescrição"
* prescricao.prescritor 1..1 Reference(Resource) "Prescritor" "Profissional prescritor."
* prescricao.posologia 0..1 string "Posologia em texto" "Prescrição não estruturada."
* prescricao.orientacoes 0..1 string "Orientações de uso" "Orientações de uso"
* prescricao.frequencia 0..1 Timing "Frequência e turno" "Intervalo entre doses e turno do dia."
* prescricao.seNecessario 0..1 boolean "Uso se necessário" "Uso se necessário"
* prescricao.via 1..1 CodeableConcept "Via de administração" "Via de administração"
* prescricao.dose 1..1 Quantity "Dose" "Dose"
* prescricao.duracao 1..1 Period "Duração / validade" "Duração / validade"
* prescricao.quantidadeTotal 0..1 Quantity "Total do tratamento" "Total do tratamento"
* planoCuidados 0..* BackboneElement "Plano de cuidados" "Instruções e recomendações para depois da alta."
* planoCuidados.descricao 1..1 string "Descrição" "Plano, instruções e recomendações."
* planoCuidados.situacao 1..1 code "Estado do plano" "Estado do plano"
* planoCuidados.atividade 0..* BackboneElement "Atividade programada" "Consulta, exame, retorno."
* capacidadeFuncional 0..* BackboneElement "Capacidade funcional" "Restrições funcionais e incapacidades na alta."
* capacidadeFuncional.achado 1..1 CodeableConcept "Achado funcional" "Capacidade ou incapacidade."
* capacidadeFuncional.situacao 1..1 CodeableConcept "Estado" "Estado"
* capacidadeFuncional.grau 0..1 CodeableConcept "Grau" "Grau da incapacidade, com a escala aplicada."

Mapping: SumarioAltaMLParaBRCore
Source: SumarioAltaML
Target: "https://br-core.saude.gov.br/fhir"
Id: br-core
Title: "BR-Core (refatoração)"
Description: "Elemento FHIR do BR-Core 1.3.0 usado neste guia."
* documento -> "Bundle (rnds-documento-sumarioalta) + Composition (rnds-sumarioalta, sobre br-core-composition)"
* documento.identificador -> "Bundle.identifier; Composition.identifier"
* documento.dataHora -> "Composition.date; Bundle.timestamp"
* documento.situacao -> "Composition.status (composition-status)"
* documento.tipo -> "Composition.type = LOINC 18842-5"
* documento.autor -> "Composition.author (br-core-practitioner / practitionerrole)"
* documento.atestador -> "Composition.attester (mode = legal)"
* documento.custodiante -> "Composition.custodian (br-core-organization)"
* documento.documentoSubstituido -> "Composition.relatesTo (replaces)"
* individuo -> "Composition.subject (br-core-patient)"
* contatoAssistencial -> "Composition.encounter (br-core-encounter)"
* contatoAssistencial.modalidade -> "Encounter.class (BRModalidadeAssistencial)"
* contatoAssistencial.modalidadeTelessaude -> "Encounter.type"
* contatoAssistencial.carater -> "Encounter.priority (BRCaraterAtendimento)"
* contatoAssistencial.admissao -> "Encounter.period.start"
* contatoAssistencial.alta -> "Encounter.period.end"
* contatoAssistencial.procedencia -> "Encounter.hospitalization.admitSource (BRProcedencia)"
* contatoAssistencial.motivoDesfecho -> "Encounter.hospitalization.dischargeDisposition (BRMotivoDesfecho)"
* contatoAssistencial.motivoAtendimento -> "Encounter.reasonReference"
* contatoAssistencial.profissional -> "Encounter.participant"
* contatoAssistencial.profissional.papel -> "Encounter.participant.type (BRResponsabilidadeParticipante)"
* contatoAssistencial.profissional.individuo -> "Encounter.participant.individual (br-core-practitioner / practitionerrole)"
* contatoAssistencial.equipe -> "CareTeam (br-core-careteam)"
* contatoAssistencial.local -> "Encounter.location (br-core-location)"
* contatoAssistencial.estabelecimento -> "Encounter.serviceProvider (br-core-organization)"
* contatoAssistencial.contatoAnterior -> "Encounter.partOf"
* contatoAssistencial.resumoEvolucao -> "Encounter.text"
* contatoAssistencial.informacoesAdicionais -> "Encounter.text ou Composition.section.text"
* diagnosticoAdmissao -> "rnds-sumarioalta section:diagnosticosAdmissao (LOINC 42347-5) → Condition (br-core-condition)"
* diagnosticoAdmissao.codigo -> "Condition.code (BRCID10)"
* diagnosticoAdmissao.situacao -> "Condition.clinicalStatus (condition-clinical + suplemento pt-BR)"
* diagnosticoAdmissao.nota -> "Condition.note"
* diagnosticoAvaliado -> "rnds-sumarioalta section:diagnosticosAvaliados (LOINC 57852-6) → Condition (br-core-condition); papel em Encounter.diagnosis.use"
* diagnosticoAvaliado.codigo -> "Condition.code (BRCID10)"
* diagnosticoAvaliado.papel -> "Encounter.diagnosis.use / rank"
* diagnosticoAvaliado.situacao -> "Condition.clinicalStatus"
* alergia -> "rnds-sumarioalta section:alergiasIntolerancias (LOINC 48765-2) → AllergyIntolerance (br-core-allergyintolerance)"
* alergia.agente -> "AllergyIntolerance.code (CBARA + SNOMED CT; BRMedicamento; BRImunobiologico)"
* alergia.categoria -> "AllergyIntolerance.category"
* alergia.tipo -> "AllergyIntolerance.type"
* alergia.grauCerteza -> "AllergyIntolerance.verificationStatus"
* alergia.criticidade -> "AllergyIntolerance.criticality"
* alergia.instalacao -> "AllergyIntolerance.onset[x]"
* alergia.manifestacao -> "AllergyIntolerance.reaction.manifestation (SNOMED CT; MedDRA adicional)"
* alergia.evolucao -> "AllergyIntolerance.note"
* procedimento -> "rnds-sumarioalta section:procedimentosRealizados (LOINC 47519-4) → Procedure (br-core-procedure)"
* procedimento.codigo -> "Procedure.code (BRProcedimentosNacionais)"
* procedimento.situacao -> "Procedure.status (event-status + suplemento pt-BR)"
* procedimento.momento -> "Procedure.performed[x]"
* procedimento.quantidade -> "sem elemento no Procedure; produção na camada financeira (Claim)"
* procedimento.executante -> "Procedure.performer.actor"
* procedimento.funcao -> "Procedure.performer.function (performer-role, SNOMED CT)"
* procedimento.estabelecimentoTerceiro -> "Procedure.performer.onBehalfOf"
* procedimento.autorizacao -> "Claim/ClaimResponse (camada financeira)"
* procedimento.resultado -> "Procedure.note / outcome"
* prescricao -> "rnds-sumarioalta section:prescricaoAlta (LOINC 8654-6) → MedicationRequest (br-core-medicationrequest)"
* prescricao.medicamento -> "MedicationRequest.medicationReference (br-core-medication, BRMedicamento)"
* prescricao.dataPrescricao -> "MedicationRequest.authoredOn"
* prescricao.prescritor -> "MedicationRequest.requester"
* prescricao.posologia -> "MedicationRequest.dosageInstruction.text"
* prescricao.orientacoes -> "MedicationRequest.dosageInstruction.patientInstruction"
* prescricao.frequencia -> "MedicationRequest.dosageInstruction.timing (repeat.period, repeat.when)"
* prescricao.seNecessario -> "MedicationRequest.dosageInstruction.asNeeded[x]"
* prescricao.via -> "MedicationRequest.dosageInstruction.route (EDQM, IPS)"
* prescricao.dose -> "MedicationRequest.dosageInstruction.doseAndRate.dose[x]"
* prescricao.duracao -> "MedicationRequest.dispenseRequest.validityPeriod"
* prescricao.quantidadeTotal -> "MedicationRequest.dispenseRequest.quantity"
* planoCuidados -> "rnds-sumarioalta section:planoCuidados (LOINC 18776-5) → CarePlan (br-core-careplan)"
* planoCuidados.descricao -> "CarePlan.description"
* planoCuidados.situacao -> "CarePlan.status (request-status + suplemento pt-BR)"
* planoCuidados.atividade -> "CarePlan.activity.detail (BRSubgrupoTabelaSUS)"
* capacidadeFuncional -> "rnds-sumarioalta section:capacidadeFuncional (LOINC 47420-5) → Condition (br-core-capacidadefuncional)"
* capacidadeFuncional.achado -> "Condition.code (BRCapacidadeFuncional, SNOMED CT; CID-10 adicional)"
* capacidadeFuncional.situacao -> "Condition.clinicalStatus"
* capacidadeFuncional.grau -> "Condition.stage"

Mapping: SumarioAltaMLParaSAIG
Source: SumarioAltaML
Target: "http://www.saude.gov.br/fhir/r4"
Id: sa-ig
Title: "SA-IG da RNDS (legado)"
Description: "Elemento ou perfil do SA-IG da RNDS que carrega a mesma informação hoje."
* documento -> "Bundle + Composition (BRSumarioAlta / BRConjuntoMinimoDados-1.1)"
* documento.identificador -> "não existe (Composition.identifier 0..0 no CMD)"
* documento.dataHora -> "Composition.date"
* documento.situacao -> "Composition.status (BREstadoDocumento-1.0)"
* documento.tipo -> "Composition.type (BRTipoDocumento-1.0)"
* documento.autor -> "Composition.author.identifier (BRPessoaJuridicaProfissionalLiberal-1.0)"
* documento.atestador -> "não existe (attester 0..0)"
* documento.custodiante -> "não existe (custodian 0..0)"
* documento.documentoSubstituido -> "Composition.relatesTo"
* individuo -> "Composition.subject.identifier (BRIndividuo-1.0) ou extensão unidentifiedPatient"
* contatoAssistencial -> "seção informacoesContatoAssistencial (BRContatoAssistencial-1.0)"
* contatoAssistencial.modalidade -> "Encounter.class; também Composition.category no CMD"
* contatoAssistencial.modalidadeTelessaude -> "Encounter.type (BRModalidadeTelessaude)"
* contatoAssistencial.carater -> "Encounter.priority"
* contatoAssistencial.admissao -> "Encounter.period.start"
* contatoAssistencial.alta -> "Encounter.period.end"
* contatoAssistencial.procedencia -> "Encounter.hospitalization.admitSource"
* contatoAssistencial.motivoDesfecho -> "Encounter.hospitalization.dischargeDisposition"
* contatoAssistencial.motivoAtendimento -> "Encounter.reasonReference"
* contatoAssistencial.profissional -> "Encounter.participant (+ extensões function e team)"
* contatoAssistencial.profissional.papel -> "Encounter.participant.type"
* contatoAssistencial.profissional.individuo -> "Encounter.participant.individual"
* contatoAssistencial.equipe -> "extensão team / BRIdentificacaoEquipe"
* contatoAssistencial.local -> "Encounter.location"
* contatoAssistencial.estabelecimento -> "Encounter.serviceProvider.identifier"
* contatoAssistencial.contatoAnterior -> "Encounter.partOf"
* contatoAssistencial.resumoEvolucao -> "seção resumoEvolucaoClinica (ClinicalImpression.summary)"
* contatoAssistencial.informacoesAdicionais -> "seção informacoesAdicionais (BRObservacaoDescritiva-1.0) e extensão otherInformations"
* diagnosticoAdmissao -> "seção problemasDiagnosticosAvaliados (BRProblemaDiagnostico)"
* diagnosticoAdmissao.codigo -> "Condition.code (BRProblemaDiagnostico)"
* diagnosticoAdmissao.situacao -> "Condition.clinicalStatus (BREstadoResolucaoDiagnosticoProblema-1.0)"
* diagnosticoAdmissao.nota -> "Condition.note"
* diagnosticoAvaliado -> "seção problemasDiagnosticosAvaliados; Encounter.diagnosis:problemAndDiagnosis"
* diagnosticoAvaliado.codigo -> "Condition.code"
* diagnosticoAvaliado.papel -> "Encounter.diagnosis.rank"
* diagnosticoAvaliado.situacao -> "Condition.clinicalStatus"
* alergia -> "seção alergiaReacaoAdversa (BRAlergiaReacaoAdversa-1.0)"
* alergia.agente -> "AllergyIntolerance.code (BRAlergenos-1.0)"
* alergia.categoria -> "AllergyIntolerance.category (BRCategoriaAgenteAlergiasReacoesAdversas-1.0)"
* alergia.tipo -> "AllergyIntolerance.type"
* alergia.grauCerteza -> "AllergyIntolerance.verificationStatus (BRGrauCertezaAlergiasReacoesAdversas-1.0)"
* alergia.criticidade -> "AllergyIntolerance.criticality (BRCriticidadeAlergiasReacoesAdversas-1.0)"
* alergia.instalacao -> "AllergyIntolerance.onset[x]"
* alergia.manifestacao -> "AllergyIntolerance.reaction.manifestation (MedDRA, máx. 1)"
* alergia.evolucao -> "AllergyIntolerance.note"
* procedimento -> "seção procedimentosRealizados (BRProcedimentoRealizado-1.0); Encounter.diagnosis:procedure"
* procedimento.codigo -> "Procedure.code (BRProcedimentosNacionais-1.0)"
* procedimento.situacao -> "Procedure.status (BREstadoEvento-1.0)"
* procedimento.momento -> "Procedure.performed[x]"
* procedimento.quantidade -> "extensão quantity (BRQuantidade-1.0)"
* procedimento.executante -> "Procedure.performer:practitioner.actor"
* procedimento.funcao -> "Procedure.performer.function (BROcupacao-1.0, CBO)"
* procedimento.estabelecimentoTerceiro -> "Procedure.performer.onBehalfOf"
* procedimento.autorizacao -> "Procedure.identifier (type AUTH)"
* procedimento.resultado -> "Procedure.note"
* prescricao -> "seção prescricaoAlta → BRRegistroPrescricaoMedicamento → BRPrescricaoMedicamento"
* prescricao.medicamento -> "MedicationRequest.medication[x] (BRPrescricaoNaoEstruturada, texto livre)"
* prescricao.dataPrescricao -> "MedicationRequest.authoredOn"
* prescricao.prescritor -> "MedicationRequest.recorder.identifier (requester = estabelecimento)"
* prescricao.posologia -> "MedicationRequest.dosageInstruction.text"
* prescricao.orientacoes -> "MedicationRequest.dosageInstruction.patientInstruction"
* prescricao.frequencia -> "timing + extensões BRIntervaloDoses e BRTurno"
* prescricao.seNecessario -> "MedicationRequest.dosageInstruction.asNeeded[x]"
* prescricao.via -> "MedicationRequest.dosageInstruction.route (BRViaAdministracao-1.0)"
* prescricao.dose -> "MedicationRequest.dosageInstruction.maxDosePerAdministration"
* prescricao.duracao -> "MedicationRequest.dispenseRequest.validityPeriod"
* prescricao.quantidadeTotal -> "MedicationRequest.dispenseRequest.quantity"
* planoCuidados -> "seção planoCuidados (BRPlanoCuidados-1.0)"
* planoCuidados.descricao -> "CarePlan.description"
* planoCuidados.situacao -> "CarePlan.status (BREstadoSolicitacao-1.0)"
* planoCuidados.atividade -> "não existe (activity 0..0)"
* capacidadeFuncional -> "seção restricaoFuncionalIncapacidadeSaude (BRRestricaoFuncionalIncapacidadeSaude-1.0)"
* capacidadeFuncional.achado -> "Condition.code.text (texto livre)"
* capacidadeFuncional.situacao -> "Condition.clinicalStatus (BREstadoRestricaoFuncionalIncapacidadeSaude-1.0)"
* capacidadeFuncional.grau -> "não existe"
