// GERADO por scripts/traducao_ptbr.py. Não edite à mão.
RuleSet: TraducaoPtBrAlergiaSumarioAlta
* . ^short = "Alergia ou Intolerância do Sumário de Alta"
* . ^definition = "Alergia ou intolerância registrada na internação. Agente e manifestação em SNOMED CT (base do CBARA), com códigos nacionais aceitos. O BR-Core mantém a ligação required com BRAlergenos; por isso o SNOMED CT entra como coding adicional enquanto o BRAlergenos não incluir SNOMED (ver débitos técnicos)."
* code.id ^short = "Identificador do elemento"
* code.id ^definition = "Identificador único do elemento dentro do recurso, para referências internas."
* code.extension ^short = "Extensões adicionais"
* code.extension ^definition = "Extensões que acrescentam informação não prevista no modelo base."
* code.coding ^short = "Código em um sistema de codificação"
* code.coding ^definition = "Referência a um código de um sistema de codificação."
* code.coding[snomed] ^definition = "Referência a um código de um sistema de codificação."
* code.coding[snomed].id ^short = "Identificador do elemento"
* code.coding[snomed].id ^definition = "Identificador único do elemento dentro do recurso, para referências internas."
* code.coding[snomed].extension ^short = "Extensões adicionais"
* code.coding[snomed].extension ^definition = "Extensões que acrescentam informação não prevista no modelo base."
* code.coding[snomed].system ^short = "Sistema de codificação"
* code.coding[snomed].system ^definition = "URL do sistema de codificação."
* code.coding[snomed].version ^short = "Versão"
* code.coding[snomed].version ^definition = "Versão de negócio do artefato."
* code.coding[snomed].code ^short = "Código"
* code.coding[snomed].code ^definition = "Código que identifica o conceito."
* code.coding[snomed].display ^short = "Descrição do código"
* code.coding[snomed].display ^definition = "Representação textual do código."
* code.coding[snomed].userSelected ^short = "Selecionado pelo usuário"
* code.coding[snomed].userSelected ^definition = "Indica que o código foi escolhido diretamente pelo usuário."
* code.text ^short = "Narrativa legível do recurso"
* code.text ^definition = "Resumo textual do recurso, para leitura humana."
